<?php require __DIR__ . '/includes/header.phtml'; ?>

<form action="/admin/usuario/editar?id=<?=$id;?>" method="post">

    <div class="form-group">
        <label>Nome Completo</label>
        <input type="text" name="name" class="form-control" value="<?= $user['name']; ?>">
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" class="form-control" value="<?= $user['email']; ?>">
    </div>

    <div class="form-group">
        <label>Senha</label>
        <input type="password" name="password" class="form-control">
    </div>

    <button type="submit" class="btn btn-lg btn-success">Atualizar</button>
</form>

<?php require __DIR__ . '/includes/footer.phtml'; ?>