<?php require __DIR__ . '/includes/header.phtml'; ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?= $user['name']; ?></td>
                <td><?= $user['email']; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php require __DIR__ . '/includes/footer.phtml'; ?>